application:
  name: prod环境 @artifactId@
  version: prod环境 @version@
developer:
  name: prod环境 andy
  website: prod环境 http://lianspring.xyz
  qq: prod环境 andy@sina.com
  phone-number: prod环境 18924229997